<?php
#### Generated by Html to PHP converter By Disipal Site (www.disipal.net) ####


echo"<!DOCTYPE html>"
  . " <head>"
  . " <meta charset=\"utf-8\">"
  . " <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">"
  . " <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
  . "   <title>My title</title>"
  . " </head>"
  . " <body>"
  . "   <h1>THE COMEDY OF THAILAND</h1>"
  . "   <p>By นายธนบดี จงศิริ รหัส 63070074</p>"
  . "   <h2>สิ่งที่เกิดขึ้น</h2>"
  . "   <img src=\"gg.jpg\" width=\"70%\">"
  . "   <p> ---------------------------------- </p>"
  . "   <br>"
  . "   <h2>ข่าวที่ออก</h2>"
  . "   <img src=\"news.jpg\" width=\"70%\">"
  . "   <p>ขส.ต.ท. วุฒิชัย ยืนยันว่าในวันเกิดเหตุวันที่ 26 ตุลาคม ขณะนั่งรถกลับจากการปฏิบัติหน้าที่ และระหว่างลงจากรถได้เห็นป้ายข้อความติดอยู่ข้างรถบัสที่ใช้ขนส่งกำลังพล จำนวน 2 แผ่น จึงได้ดึงออกเพื่อจะนำเอาไปทิ้งถังขยะ แต่มีเพื่อนที่อยากเห็นจึงยกข้อความชูให้เพื่อนดู โดยทราบว่ามีการถ่ายภาพและแชร์กันในกลุ่มไลน์เพื่อน แต่ไม่ทราบว่าภาพหลุดลงโซเซียลได้อย่างไร<p>"
  . "   <br>"
  . "   <a href=\"https://thestandard.co/police-border-patrol-raising-protest-signs/\">ข่าวแหล่งที่มา THE STANDARD</a>"
  . "   </body>"
 ."";

?>
