<?php
#### Generated by Html to PHP converter By Disipal Site (www.disipal.net) ####


echo"<!DOCTYPE html>"
  . "html lang=\"th\">"
  . " <head>"
  . " <meta charset=\"utf-8\">"
  . " <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">"
  . " <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
  . " <meta name=\"Keywords\" content=\"คนดังหลั่งน้ำตา, \"> <link rel=\"shortcut icon\" href=\"pracharat.png\">"
  . "   <title>My title</title>"
  . " </head>"
  . " <body>"
  . "   <h1>THE STANDUP</h1>"
  . "   <p>My First Paragraph</p>"
  . "   <img src=\"mypic.jpg\" alt=\"หมา\" width=\"100%\">"
  . "   <br>"
  . "   <a href=\"http://www.it.kmitl.ac.th\">This is link</a>"
  . "    <h2>The list</h2>"
  . "   <uI>"
  . "     <li>Google</li>"
  . "     <li>Google</li>"
  . "     <li>Google</li>"
  . "   </uI>"
  . "    </body>"
  . "/html>"
 ."";

?>
