<?php
#### Generated by Html to PHP converter By Disipal Site (www.disipal.net) ####


echo"<!DOCTYPE html>"
  . "html>"
  . " <head>"
  . " <meta charset=\"utf-8\">"
  . " <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">"
  . " <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
  . " <meta name=\"Keywords\" content=\"คนดังหลั่งน้ำตา, \"> <link rel=\"shortcut icon\" href=\"pracharat.png\">"
  . "   <title>My title</title>"
  . " </head>"
  . " <body>"
  . "   <h1>THE STANDUP</h1>"
  . "   <p>\"ชัยวุฒิ\"เปรียบม็อบไม่ได้ทะเลาะกับหมา \"วิโรจน์\" ท้วง แบบนี้เท่ากับ \"บิ๊กตู่\" เป็นหมา<p>"
  . "   <p>By นายธนบดี จงศิริ รหัส 63070074</p>"
  . "   <img src=\"mypic.jpg\" alt=\"หมา\" width=\"70%\">"
  . "   <br>"
  . "   <a href=\"https://www.youtube.com/watch?v=uuXjocXd51w\">คลิปแหล่งที่มา</a>"
  . "   <br><br><br>"
  . "   <img src=\"mypic.jpg\" alt=\"หมา\" width=\"70%\">"
  . "   <br>"
  . "   <a href=\"https://www.youtube.com/watch?v=uuXjocXd51w\">คลิปแหล่งที่มา</a>"
  . "   </body>"
  . "/html>"
 ."";

?>
